create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text unique not null,
  slug text unique not null,
  sort_order int default 0
);

create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  excerpt text default '',
  content jsonb not null default '[]'::jsonb,
  category text default '未分类',
  author text default 'Neko',
  published_at timestamptz default now(),
  read_minutes int default 1,
  views bigint default 0,
  likes bigint default 0,
  image_url text not null default '',
  featured boolean not null default false,
  published boolean not null default false,
  tags text[] not null default '{}'
);

alter table public.articles add column if not exists deleted_at timestamptz;
alter table public.articles add column if not exists deleted_by uuid references auth.users(id) on delete set null;

create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  article_id bigint not null references public.articles(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  author text not null,
  message text not null check (char_length(message) between 1 and 1000),
  approved boolean not null default false,
  created_at timestamptz default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  role text default 'user' check (role in ('user','editor','admin')),
  created_at timestamptz default now()
);

alter table public.categories enable row level security;
alter table public.articles enable row level security;
alter table public.comments enable row level security;
alter table public.profiles enable row level security;

drop policy if exists "public can read categories" on public.categories;
create policy "public can read categories" on public.categories for select using (true);
drop policy if exists "public can read published articles" on public.articles;
create policy "public can read published articles" on public.articles for select using (published = true and deleted_at is null);
drop policy if exists "public can read approved comments" on public.comments;
create policy "public can read approved comments" on public.comments for select using (approved = true);
drop policy if exists "users can read own profile" on public.profiles;
create policy "users can read own profile" on public.profiles for select using (auth.uid() = id);
drop policy if exists "users can update own profile" on public.profiles;
create policy "users can update own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

revoke update on public.profiles from authenticated;
grant update (display_name, avatar_url) on public.profiles to authenticated;


create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name, role) values (new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email,'@',1)), 'user') on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create table if not exists public.moments (
  id bigint generated by default as identity primary key,
  content text not null check (char_length(content) between 1 and 1000),
  mood text default '动态',
  published_at timestamptz default now(),
  tags text[] not null default '{}',
  image_url text not null default '',
  published boolean not null default true
);

alter table public.moments enable row level security;
drop policy if exists "public can read published moments" on public.moments;
create policy "public can read published moments" on public.moments for select using (published = true);

-- RLS policies filter rows, while PostgreSQL grants allow the API roles to
-- access the tables at all. Keep public writes limited to pending comments;
-- privileged CMS writes use the server-only service role.
grant usage on schema public to anon, authenticated, service_role;
grant select on public.categories, public.articles, public.comments, public.moments to anon, authenticated;
grant insert on public.comments to anon, authenticated;
grant select on public.profiles to authenticated;
grant all privileges on public.categories, public.articles, public.comments, public.profiles, public.moments to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'media',
  'media',
  true,
  52428800,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif', 'audio/mpeg', 'audio/wav', 'audio/ogg', 'video/mp4', 'video/webm']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Direct resumable uploads use the signed-in CMS user's access token. Keep
-- uploads scoped to the public media bucket and its uploads directory.
create or replace function public.is_cms_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid()
      and role in ('admin', 'editor')
  );
$$;
revoke all on function public.is_cms_user() from public;
grant execute on function public.is_cms_user() to authenticated;

drop policy if exists "cms users can upload media" on storage.objects;
create policy "cms users can upload media"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'media'
  and (storage.foldername(name))[1] = 'uploads'
  and (select public.is_cms_user())
);

-- Safe upgrades for projects created with an earlier version of this schema.
alter table public.comments alter column approved set default false;
update public.comments set approved = false where approved is null;
alter table public.comments alter column approved set not null;
alter table public.moments add column if not exists image_url text default '';
create index if not exists articles_public_feed_idx on public.articles (published, published_at desc);
create index if not exists articles_featured_idx on public.articles (featured, published, published_at desc);
create index if not exists articles_deleted_at_idx on public.articles (deleted_at, published_at desc);
create index if not exists moments_public_feed_idx on public.moments (published, published_at desc);
create index if not exists comments_moderation_idx on public.comments (approved, created_at desc);

create table if not exists public.carousel_items (
  id bigint generated by default as identity primary key,
  article_id bigint not null unique references public.articles(id) on delete cascade,
  sort_order int not null default 0,
  enabled boolean not null default true,
  custom_title text not null default '',
  custom_excerpt text not null default '',
  image_url text not null default '',
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint carousel_valid_window check (ends_at is null or starts_at is null or ends_at > starts_at)
);
create index if not exists carousel_active_order_idx on public.carousel_items (enabled, sort_order);
alter table public.carousel_items enable row level security;
drop policy if exists "public can read active carousel" on public.carousel_items;
create policy "public can read active carousel" on public.carousel_items for select using (enabled = true and (starts_at is null or starts_at <= now()) and (ends_at is null or ends_at > now()));
grant select on public.carousel_items to anon, authenticated;
grant all privileges on public.carousel_items to service_role;
drop policy if exists "public can create comments" on public.comments;
drop policy if exists "public can create pending comments" on public.comments;
create policy "public can create pending comments" on public.comments for insert with check (approved = false and char_length(message) between 1 and 1000);

alter table public.categories add column if not exists description text not null default '';
alter table public.categories add column if not exists color text not null default '#ec4899';
alter table public.categories add column if not exists visible boolean not null default true;
create table if not exists public.site_settings (
  id boolean primary key default true check (id = true),
  site_name text not null default 'NekoPress',
  site_description text not null default '动漫、游戏、开发与生活灵感的个人内容站。',
  logo_url text not null default '',
  default_cover_url text not null default '/images/default-cover.svg',
  posts_per_page int not null default 6 check (posts_per_page between 1 and 20),
  comments_require_approval boolean not null default true,
  seo_title text not null default 'NekoPress',
  seo_description text not null default '动漫、游戏、开发与生活灵感的个人内容站。',
  updated_at timestamptz not null default now()
);
insert into public.site_settings (id) values (true) on conflict (id) do nothing;
alter table public.site_settings enable row level security;
drop policy if exists "public can read site settings" on public.site_settings;
create policy "public can read site settings" on public.site_settings for select using (true);
grant select on public.site_settings to anon, authenticated;
grant all privileges on public.site_settings to service_role;

create table if not exists public.article_versions (
  id bigint generated by default as identity primary key,
  article_id bigint not null references public.articles(id) on delete cascade,
  snapshot jsonb not null,
  change_type text not null default 'update' check (change_type in ('update','restore','trash')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists article_versions_article_idx on public.article_versions (article_id, created_at desc);
alter table public.article_versions enable row level security;
revoke all on public.article_versions from anon, authenticated;
grant all privileges on public.article_versions to service_role;
grant usage, select on all sequences in schema public to service_role;
drop policy if exists "public can create pending comments" on public.comments;
create policy "public can create comments according to settings" on public.comments for insert with check (approved = not coalesce((select comments_require_approval from public.site_settings where id = true), true) and char_length(message) between 1 and 1000);
create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_email text not null default '',
  action text not null,
  resource text not null,
  resource_id text not null default '',
  label text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists admin_audit_logs_created_at_idx on public.admin_audit_logs(created_at desc);
alter table public.admin_audit_logs enable row level security;
revoke all on public.admin_audit_logs from anon, authenticated;
grant all on public.admin_audit_logs to service_role;
create table if not exists public.media_assets (
  id uuid primary key default gen_random_uuid(),
  path text not null unique,
  public_url text not null unique,
  original_name text not null,
  mime_type text not null,
  media_type text not null check (media_type in ('image','audio','video')),
  size_bytes bigint not null default 0 check (size_bytes >= 0),
  width int check (width is null or width > 0),
  height int check (height is null or height > 0),
  duration_seconds numeric check (duration_seconds is null or duration_seconds >= 0),
  status text not null default 'ready' check (status in ('uploading','ready','failed','trash')),
  content_hash text,
  uploaded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.media_references (
  id bigint generated by default as identity primary key,
  media_id uuid not null references public.media_assets(id) on delete cascade,
  resource_type text not null check (resource_type in ('article','moment','carousel','site_settings')),
  resource_id text not null,
  field_name text not null,
  created_at timestamptz not null default now(),
  unique (media_id, resource_type, resource_id, field_name)
);

create index if not exists media_assets_created_idx on public.media_assets(created_at desc);
create index if not exists media_assets_type_status_idx on public.media_assets(media_type,status,created_at desc);
create index if not exists media_assets_content_hash_idx on public.media_assets(content_hash) where content_hash is not null and status = 'ready';
create index if not exists media_references_media_idx on public.media_references(media_id);
create index if not exists media_references_resource_idx on public.media_references(resource_type,resource_id);

alter table public.media_assets enable row level security;
alter table public.media_references enable row level security;
revoke all on public.media_assets, public.media_references from anon, authenticated;
grant all on public.media_assets, public.media_references to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.sync_article_media_references()
returns trigger language plpgsql security definer set search_path=public as $$
declare target_id text;
begin
  target_id := case when tg_op='DELETE' then old.id::text else new.id::text end;
  delete from public.media_references where resource_type='article' and resource_id=target_id;
  if tg_op <> 'DELETE' then
    insert into public.media_references(media_id,resource_type,resource_id,field_name)
    select id,'article',new.id::text,'cover' from public.media_assets where public_url=new.image_url and new.image_url<>''
    on conflict do nothing;
    insert into public.media_references(media_id,resource_type,resource_id,field_name)
    select id,'article',new.id::text,'content' from public.media_assets
    where public_url<>'' and position(public_url in new.content::text)>0
    on conflict do nothing;
  end if;
  if tg_op='DELETE' then return old; end if;
  return new;
end $$;

create or replace function public.sync_moment_media_references()
returns trigger language plpgsql security definer set search_path=public as $$
declare target_id text;
begin
  target_id := case when tg_op='DELETE' then old.id::text else new.id::text end;
  delete from public.media_references where resource_type='moment' and resource_id=target_id;
  if tg_op <> 'DELETE' and new.image_url<>'' then
    insert into public.media_references(media_id,resource_type,resource_id,field_name)
    select id,'moment',new.id::text,'image' from public.media_assets where public_url=new.image_url
    on conflict do nothing;
  end if;
  if tg_op='DELETE' then return old; end if;
  return new;
end $$;

create or replace function public.sync_carousel_media_references()
returns trigger language plpgsql security definer set search_path=public as $$
declare target_id text;
begin
  target_id := case when tg_op='DELETE' then old.id::text else new.id::text end;
  delete from public.media_references where resource_type='carousel' and resource_id=target_id;
  if tg_op <> 'DELETE' and new.image_url<>'' then
    insert into public.media_references(media_id,resource_type,resource_id,field_name)
    select id,'carousel',new.id::text,'image' from public.media_assets where public_url=new.image_url
    on conflict do nothing;
  end if;
  if tg_op='DELETE' then return old; end if;
  return new;
end $$;

create or replace function public.sync_settings_media_references()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  delete from public.media_references where resource_type='site_settings' and resource_id='global';
  if tg_op <> 'DELETE' then
    insert into public.media_references(media_id,resource_type,resource_id,field_name)
    select id,'site_settings','global','logo' from public.media_assets where public_url=new.logo_url and new.logo_url<>''
    on conflict do nothing;
    insert into public.media_references(media_id,resource_type,resource_id,field_name)
    select id,'site_settings','global','default_cover' from public.media_assets where public_url=new.default_cover_url and new.default_cover_url<>''
    on conflict do nothing;
  end if;
  if tg_op='DELETE' then return old; end if;
  return new;
end $$;

create or replace function public.sync_new_media_asset_references()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  delete from public.media_references where media_id=new.id;
  insert into public.media_references(media_id,resource_type,resource_id,field_name)
  select new.id,'article',id::text,'cover' from public.articles where image_url=new.public_url and new.public_url<>''
  on conflict do nothing;
  insert into public.media_references(media_id,resource_type,resource_id,field_name)
  select new.id,'article',id::text,'content' from public.articles where new.public_url<>'' and position(new.public_url in content::text)>0
  on conflict do nothing;
  insert into public.media_references(media_id,resource_type,resource_id,field_name)
  select new.id,'moment',id::text,'image' from public.moments where image_url=new.public_url and new.public_url<>''
  on conflict do nothing;
  insert into public.media_references(media_id,resource_type,resource_id,field_name)
  select new.id,'carousel',id::text,'image' from public.carousel_items where image_url=new.public_url and new.public_url<>''
  on conflict do nothing;
  insert into public.media_references(media_id,resource_type,resource_id,field_name)
  select new.id,'site_settings','global','logo' from public.site_settings where logo_url=new.public_url and new.public_url<>''
  on conflict do nothing;
  insert into public.media_references(media_id,resource_type,resource_id,field_name)
  select new.id,'site_settings','global','default_cover' from public.site_settings where default_cover_url=new.public_url and new.public_url<>''
  on conflict do nothing;
  return new;
end $$;

drop trigger if exists sync_article_media_refs on public.articles;
create trigger sync_article_media_refs after insert or update or delete on public.articles for each row execute function public.sync_article_media_references();
drop trigger if exists sync_moment_media_refs on public.moments;
create trigger sync_moment_media_refs after insert or update or delete on public.moments for each row execute function public.sync_moment_media_references();
drop trigger if exists sync_carousel_media_refs on public.carousel_items;
create trigger sync_carousel_media_refs after insert or update or delete on public.carousel_items for each row execute function public.sync_carousel_media_references();
drop trigger if exists sync_settings_media_refs on public.site_settings;
create trigger sync_settings_media_refs after insert or update or delete on public.site_settings for each row execute function public.sync_settings_media_references();
drop trigger if exists sync_new_media_asset_refs on public.media_assets;
create trigger sync_new_media_asset_refs after insert or update on public.media_assets for each row execute function public.sync_new_media_asset_references();
