import Link from "next/link";
import { AlertCircle, ArrowRight, Eye, FileText, ImageOff, MessageSquare, Plus, Sparkles } from "lucide-react";
import { getAdminDashboardData } from "@/lib/admin-data";
import { AdminPublishingChart } from "@/components/admin-publishing-chart";

export default async function AdminPage(){
  const result=await getAdminDashboardData();
  if(!result.ok)return <div className="panel p-6 text-sm text-red-500">工作台读取失败：{result.error}</div>;
  const data=result.data;
  const cards=[{label:"全部文章",value:data.articleTotal,note:`${data.publishedArticles} 篇已发布`,icon:FileText,color:"text-blue-500 bg-blue-500/10"},{label:"待审核评论",value:data.pendingCommentTotal,note:`共 ${data.commentTotal} 条评论`,icon:MessageSquare,color:"text-amber-500 bg-amber-500/10"},{label:"动态",value:data.momentTotal,note:`${data.publishedMoments} 条公开`,icon:Sparkles,color:"text-pink-500 bg-pink-500/10"},{label:"总浏览量",value:data.totalViews.toLocaleString(),note:"全部文章累计",icon:Eye,color:"text-emerald-500 bg-emerald-500/10"}];
  return <div className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-pink-500">Dashboard</p><h2 className="mt-1 text-2xl font-black tracking-tight">欢迎回来</h2><p className="mt-1 text-sm text-zinc-500">这里是网站今天需要关注的内容。</p></div><div className="flex gap-2"><Link href="/admin/moments/new" className="rounded-xl border border-black/10 bg-white px-4 py-2.5 text-sm font-black dark:border-white/10 dark:bg-white/5">发动态</Link><Link href="/admin/articles/new" className="btn-primary !rounded-xl"><Plus size={15}/>写文章</Link></div></header>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(card=>{const Icon=card.icon;return <div className="panel p-5" key={card.label}><div className="flex items-start justify-between"><div><p className="text-xs font-bold text-zinc-500">{card.label}</p><b className="mt-2 block text-3xl tracking-tight">{card.value}</b></div><div className={`grid h-10 w-10 place-items-center rounded-xl ${card.color}`}><Icon size={19}/></div></div><p className="mt-4 text-xs text-zinc-400">{card.note}</p></div>})}</div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(280px,.8fr)]"><section className="panel p-5 sm:p-6"><div><h3 className="font-black">近 7 天发布趋势</h3><p className="mt-1 text-xs text-zinc-400">按文章实际发布日期统计</p></div><AdminPublishingChart items={data.publishingTrend}/></section><section className="panel p-5 sm:p-6"><div className="flex items-center justify-between"><div><h3 className="font-black">待办事项</h3><p className="mt-1 text-xs text-zinc-400">优先处理影响发布的内容</p></div><AlertCircle size={19} className="text-amber-500"/></div><div className="mt-5 grid gap-3"><Link href="/admin/comments" className="flex items-center gap-3 rounded-xl bg-amber-500/10 p-4"><MessageSquare size={18} className="text-amber-600"/><div className="min-w-0 flex-1"><b className="text-sm">{data.pendingCommentTotal} 条评论待审核</b><p className="mt-1 text-xs text-zinc-500">及时处理访客互动</p></div><ArrowRight size={15}/></Link><Link href="/admin/articles?status=draft" className="flex items-center gap-3 rounded-xl bg-blue-500/10 p-4"><FileText size={18} className="text-blue-600"/><div className="min-w-0 flex-1"><b className="text-sm">{data.draftArticles} 篇草稿待完成</b><p className="mt-1 text-xs text-zinc-500">继续编辑未发布内容</p></div><ArrowRight size={15}/></Link><Link href="/admin/articles" className="flex items-center gap-3 rounded-xl bg-red-500/10 p-4"><ImageOff size={18} className="text-red-500"/><div className="min-w-0 flex-1"><b className="text-sm">{data.missingCovers} 篇文章缺少封面</b><p className="mt-1 text-xs text-zinc-500">完善前台展示效果</p></div><ArrowRight size={15}/></Link></div></section></div>
    <div className="grid gap-6 xl:grid-cols-2"><section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-black/5 p-5 dark:border-white/10"><div><h3 className="font-black">最近文章</h3><p className="mt-1 text-xs text-zinc-400">继续编辑最近创建的内容</p></div><Link href="/admin/articles" className="text-xs font-black text-pink-500">查看全部</Link></div><div className="divide-y divide-black/5 dark:divide-white/10">{data.recentArticles.map(item=><Link href={`/admin/articles/${item.id}`} key={item.id} className="flex items-center gap-3 px-5 py-3.5 hover:bg-zinc-50 dark:hover:bg-white/[.025]"><div className="min-w-0 flex-1"><b className="block truncate text-sm">{item.title}</b><p className="mt-1 text-xs text-zinc-400">{item.category} · {item.publishedAt.slice(0,10)||"未设置日期"}</p></div><span className={`rounded-md px-2 py-1 text-[10px] font-black ${item.published?"bg-emerald-500/10 text-emerald-600":"bg-zinc-500/10 text-zinc-500"}`}>{item.published?"已发布":"草稿"}</span></Link>)}{data.recentArticles.length===0&&<p className="p-6 text-sm text-zinc-500">还没有文章。</p>}</div></section>
      <section className="panel overflow-hidden"><div className="border-b border-black/5 p-5 dark:border-white/10"><h3 className="font-black">热门内容</h3><p className="mt-1 text-xs text-zinc-400">按累计浏览量排序</p></div><div className="divide-y divide-black/5 dark:divide-white/10">{data.popularArticles.map((item,index)=><Link href={`/admin/articles/${item.id}`} key={item.id} className="flex items-center gap-3 px-5 py-3.5 hover:bg-zinc-50 dark:hover:bg-white/[.025]"><span className={`grid h-7 w-7 place-items-center rounded-lg text-xs font-black ${index<3?"bg-pink-500/10 text-pink-500":"bg-zinc-500/10 text-zinc-500"}`}>{index+1}</span><b className="min-w-0 flex-1 truncate text-sm">{item.title}</b><span className="flex items-center gap-1 text-xs text-zinc-400"><Eye size={13}/>{item.views.toLocaleString()}</span></Link>)}{data.popularArticles.length===0&&<p className="p-6 text-sm text-zinc-500">暂无浏览数据。</p>}</div></section></div>
    {data.pendingComments.length>0&&<section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-black/5 p-5 dark:border-white/10"><div><h3 className="font-black">最新待审核评论</h3><p className="mt-1 text-xs text-zinc-400">来自访客的最新互动</p></div><Link href="/admin/comments" className="text-xs font-black text-pink-500">前往审核</Link></div><div className="grid divide-y divide-black/5 md:grid-cols-2 md:divide-x md:divide-y-0 dark:divide-white/10">{data.pendingComments.map(item=><div className="p-5" key={item.id}><div className="flex items-center justify-between gap-3"><b className="text-sm">{item.author}</b><time className="text-[10px] text-zinc-400">{new Date(item.createdAt).toLocaleDateString("zh-CN")}</time></div><p className="mt-2 line-clamp-2 text-sm leading-6 text-zinc-500">{item.message}</p></div>)}</div></section>}
  </div>;
}
