import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { getComments, getSiteSettings } from "@/lib/data";
import { createServerClientSafe } from "@/lib/supabase/server";
import { revalidateCommentContent } from "@/lib/revalidation";
import { consumeFixedWindow, isRecentDuplicate, recordSubmission, requestClientKey } from "@/lib/request-security";

const schema=z.object({articleId:z.number().int().positive(),author:z.string().trim().min(1).max(32).refine(value=>!/[\u0000-\u001f\u007f]/.test(value),"昵称包含无效字符"),message:z.string().trim().min(2).max(1000).refine(value=>(value.match(/https?:\/\//gi)?.length??0)<=2,"评论包含过多链接")});
export async function GET(req:NextRequest){const id=Number(req.nextUrl.searchParams.get("articleId"));if(!Number.isFinite(id))return NextResponse.json({error:"invalid articleId"},{status:400});return NextResponse.json(await getComments(id));}
export async function POST(req:NextRequest){let payload:unknown;try{payload=await req.json()}catch{return NextResponse.json({error:"请求内容格式错误"},{status:400})}const parsed=schema.safeParse(payload);if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message??"评论内容不符合要求"},{status:400});const clientKey=requestClientKey(req);const limit=consumeFixedWindow(`comment:${clientKey}`,5,10*60*1000);if(!limit.allowed)return NextResponse.json({error:"评论提交过于频繁，请稍后再试"},{status:429,headers:{"Retry-After":String(limit.retryAfterSeconds)}});const normalized={...parsed.data,author:parsed.data.author.replace(/\s+/g," "),message:parsed.data.message.replace(/\r\n/g,"\n").replace(/\n{3,}/g,"\n\n")};const duplicateKey=`${clientKey}:${normalized.articleId}:${normalized.author.toLowerCase()}:${normalized.message}`;if(isRecentDuplicate(duplicateKey,2*60*1000))return NextResponse.json({error:"请勿重复提交相同评论"},{status:409});const supabase=await createServerClientSafe();if(!supabase)return NextResponse.json({error:"评论服务尚未配置"},{status:503});const settings=await getSiteSettings();const approved=!settings.commentsRequireApproval;const {error}=await supabase.from("comments").insert({article_id:normalized.articleId,author:normalized.author,message:normalized.message,approved});if(error){console.error("[comment-create]",error);return NextResponse.json({error:"评论提交失败，请稍后重试"},{status:500})}recordSubmission(duplicateKey);if(approved)revalidateCommentContent();return NextResponse.json({ok:true,pending:!approved},{status:approved?201:202});}
