"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Check, CloudOff, Eye, History, ImagePlus, Save, Trash2 } from "lucide-react";
import type { AdminArticle } from "@/lib/types";
import { SafeImage } from "@/components/safe-image";
import { MediaPicker } from "@/components/media-picker";
import { MarkdownEditor } from "@/components/markdown-editor";

function slugify(value:string){return value.trim().toLowerCase().replace(/[^a-z0-9\s-]/g,"").replace(/\s+/g,"-").replace(/-+/g,"-")}
function localDateTime(value?:string){if(!value)return "";const date=new Date(value);date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,16)}

export function AdminArticleForm({ initial }: { initial?: AdminArticle }) {
  const router=useRouter();const [title,setTitle]=useState(initial?.title??"");const [slug,setSlug]=useState(initial?.slug??"");const [slugEdited,setSlugEdited]=useState(Boolean(initial));const [excerpt,setExcerpt]=useState(initial?.excerpt??"");const [category,setCategory]=useState(initial?.category??"日常");const [author,setAuthor]=useState(initial?.author??"Neko");const [imageUrl,setImageUrl]=useState(initial?.imageUrl??"");const [tags,setTags]=useState(initial?.tags.join(", ")??"");const [content,setContent]=useState(initial?.content.join("\n\n")??"");const [featured,setFeatured]=useState(initial?.featured??false);const [published,setPublished]=useState(initial?.published??false);const [message,setMessage]=useState(initial?"已保存":"尚未保存");const [saving,setSaving]=useState(false);const [dirty,setDirty]=useState(false);const [online,setOnline]=useState(true);const autosaveTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const revision=useRef(0);const saveQueue=useRef<Promise<boolean>>(Promise.resolve(true));const draftKey=`nekopress:article-draft:${initial?.id??"new"}`;
  const [publishAt,setPublishAt]=useState(localDateTime(initial?.publishedAt));
  const change=<T,>(setter:(value:T)=>void,value:T)=>{revision.current+=1;setter(value);setDirty(true)};
  function payload(publishValue=published){return{id:initial?.id,title,slug,excerpt,category,author,imageUrl,featured,published:publishValue,publishAt:publishAt?new Date(publishAt).toISOString():undefined,tags:tags.split(/[,，]/).map(x=>x.trim()).filter(Boolean),content:content.trim()?[content.trim()]:[]}}
  async function persist(redirectAfter=false,auto=false,publishOverride?:boolean){const publishValue=publishOverride??(auto?(initial?.published??false):published);const body=payload(publishValue);if(!body.title.trim()||!body.slug.trim()||!body.content.length){setMessage("请先填写标题、链接和正文");return false}if(body.published&&(!body.excerpt.trim()||!body.imageUrl.trim())){setMessage("发布前请补充摘要和封面");return false}const requestedRevision=revision.current;saveQueue.current=saveQueue.current.then(async()=>{setSaving(true);setMessage(auto?"正在自动保存…":body.published?"正在发布…":"正在保存草稿…");let response:Response|undefined;for(let attempt=0;attempt<(auto?2:1);attempt+=1){try{response=await fetch("/api/admin/articles",{method:initial?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(response.ok||response.status<500)break}catch{response=undefined}}setSaving(false);if(!response){setOnline(false);setMessage("网络不可用，内容已保存在本机");return false}const result=await response.json();if(!response.ok){setMessage(result.error??"保存失败，本地草稿仍保留");return false}setPublished(body.published);if(requestedRevision===revision.current){setDirty(false);localStorage.removeItem(draftKey)}setMessage(auto?"草稿已自动保存":body.published?"文章已发布":"草稿已保存");if(redirectAfter){router.push("/admin/articles");router.refresh()}return true});return saveQueue.current}
  async function save(e:FormEvent){e.preventDefault();await persist(true)}
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=""}};const on=()=>setOnline(true);const off=()=>setOnline(false);window.addEventListener("beforeunload",warn);window.addEventListener("online",on);window.addEventListener("offline",off);return()=>{window.removeEventListener("beforeunload",warn);window.removeEventListener("online",on);window.removeEventListener("offline",off)}},[dirty]);
  useEffect(()=>{const guard=(event:MouseEvent)=>{if(!dirty||event.defaultPrevented||event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;const target=event.target as Element|null;const link=target?.closest("a[href]") as HTMLAnchorElement|null;if(!link||link.target==="_blank"||link.origin!==window.location.origin||link.href===window.location.href)return;if(!window.confirm("还有未保存的修改，确定离开当前页面吗？")){event.preventDefault();event.stopImmediatePropagation()}};document.addEventListener("click",guard,true);return()=>document.removeEventListener("click",guard,true)},[dirty]);
  useEffect(()=>{if(!dirty)return;const timer=setTimeout(()=>localStorage.setItem(draftKey,JSON.stringify({...payload(),savedAt:new Date().toISOString()})),500);return()=>clearTimeout(timer)},[title,slug,excerpt,category,author,imageUrl,tags,content,featured,published,dirty,draftKey]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(!initial||initial.published||published||!dirty||saving||!online)return;if(autosaveTimer.current)clearTimeout(autosaveTimer.current);autosaveTimer.current=setTimeout(()=>{void persist(false,true)},3000);return()=>{if(autosaveTimer.current)clearTimeout(autosaveTimer.current)}},[title,slug,excerpt,category,author,imageUrl,tags,content,featured,published,dirty,saving,online]); // eslint-disable-line react-hooks/exhaustive-deps
  function restoreDraft(){try{const raw=localStorage.getItem(draftKey);if(!raw){setMessage("没有找到本地草稿");return}const draft=JSON.parse(raw);setTitle(draft.title??"");setSlug(draft.slug??"");setExcerpt(draft.excerpt??"");setCategory(draft.category??"日常");setAuthor(draft.author??"Neko");setImageUrl(draft.imageUrl??"");setTags(Array.isArray(draft.tags)?draft.tags.join(", "):"");setContent(Array.isArray(draft.content)?draft.content.join("\n\n"):"");setFeatured(Boolean(draft.featured));setPublished(Boolean(draft.published));revision.current+=1;setDirty(true);setMessage(`已恢复本地草稿${draft.savedAt?`（${new Date(draft.savedAt).toLocaleString()}）`:""}`)}catch{setMessage("本地草稿无法读取")}}
  async function upload(file:File){setMessage("正在上传图片…");const fd=new FormData();fd.append("file",file);const r=await fetch("/api/upload",{method:"POST",body:fd});const j=await r.json();if(r.ok){setImageUrl(j.url);setDirty(true);setMessage("图片上传成功，等待保存")}else setMessage(`上传失败：${j.error}`)}
  async function remove(){if(!initial||!confirm("确定将这篇文章移入回收站吗？之后可以恢复。"))return;const r=await fetch(`/api/admin/articles?id=${initial.id}`,{method:"DELETE"});if(r.ok){localStorage.removeItem(draftKey);router.push("/admin/articles");router.refresh()}else{const result=await r.json().catch(()=>null);setMessage(result?.error??"移入回收站失败")}}
  const words=content.replace(/\s/g,"").length;
  return <form onSubmit={save} className="space-y-5"><header className="sticky top-16 z-20 -mx-4 flex flex-wrap items-center justify-between gap-3 border-b border-black/5 bg-[#f6f7f9]/95 px-4 py-3 backdrop-blur-xl sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8 dark:border-white/10 dark:bg-[#0b0d12]/95"><div><p className={`flex items-center gap-1.5 text-xs font-bold ${!online?"text-red-500":dirty?"text-amber-500":"text-emerald-600"}`}>{!online?<><CloudOff size={13}/>离线，本地草稿已启用</>:dirty?"有未保存修改":<><Check size={13}/>已保存</>}</p><p aria-live="polite" className="mt-1 text-xs text-zinc-400">{message}{initial?.published&&dirty?" · 已发布文章不会自动更新":""}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={restoreDraft} className="hidden items-center gap-2 rounded-xl border border-black/10 px-3 py-2 text-xs font-black md:flex dark:border-white/10"><History size={14}/>恢复草稿</button>{initial?.published&&<Link className="flex items-center gap-2 rounded-xl border border-black/10 px-3 py-2 text-xs font-black dark:border-white/10" href={`/article/${initial.slug}`} target="_blank"><Eye size={14}/>预览</Link>}<button type="button" disabled={saving} onClick={()=>void persist(false,false,false)} className="flex items-center gap-2 rounded-xl border border-black/10 bg-white px-3 py-2 text-xs font-black dark:border-white/10 dark:bg-white/5"><Save size={14}/>保存草稿</button><button type="button" disabled={saving} onClick={()=>void persist(true,false,true)} className="btn-primary !rounded-xl !px-4 !py-2"><Save size={14}/>{saving?"处理中…":"发布"}</button></div></header>
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_310px]"><section className="panel space-y-4 p-5 sm:p-6"><input className="w-full border-0 bg-transparent text-2xl font-black tracking-[-.03em] outline-none placeholder:text-zinc-300 sm:text-3xl" placeholder="输入文章标题…" value={title} onChange={e=>{change(setTitle,e.target.value);if(!slugEdited)setSlug(slugify(e.target.value))}} required/><textarea className="field resize-none" rows={3} maxLength={500} placeholder="用一两句话介绍文章内容…" value={excerpt} onChange={e=>change(setExcerpt,e.target.value)}/><div className="border-t border-black/5 pt-4 dark:border-white/10"><div className="mb-2 flex items-center justify-between"><b className="text-sm">Markdown 正文</b><span className="text-xs text-zinc-400">{words} 字 · 约 {Math.max(1,Math.ceil(words/400))} 分钟</span></div><MarkdownEditor value={content} onChange={value=>change(setContent,value)}/></div></section>
      <aside className="space-y-4 xl:sticky xl:top-36"><section className="panel p-5"><h2 className="font-black">发布设置</h2><div className="mt-4 grid gap-4"><div className="flex items-center justify-between rounded-xl bg-black/[.03] px-3 py-2.5 text-sm font-bold dark:bg-white/5"><span>当前状态</span><span className={published?"text-emerald-600":"text-zinc-400"}>{published?(publishAt&&new Date(publishAt)>new Date()?"等待发布":"已发布"):"草稿"}</span></div><label className="text-xs font-bold text-zinc-500">发布时间（留空为立即发布）<input type="datetime-local" className="field mt-1" value={publishAt} onChange={e=>change(setPublishAt,e.target.value)}/></label><label className="flex items-center justify-between rounded-xl bg-black/[.03] px-3 py-2.5 text-sm font-bold dark:bg-white/5">首页精选<input type="checkbox" checked={featured} onChange={e=>change(setFeatured,e.target.checked)}/></label><label className="text-xs font-bold text-zinc-500">分类<input className="field mt-1" value={category} onChange={e=>change(setCategory,e.target.value)} required/></label><label className="text-xs font-bold text-zinc-500">作者<input className="field mt-1" value={author} onChange={e=>change(setAuthor,e.target.value)} required/></label><label className="text-xs font-bold text-zinc-500">链接标识<input className="field mt-1" value={slug} onChange={e=>{setSlugEdited(true);change(setSlug,slugify(e.target.value))}} placeholder="my-first-post" required/></label><label className="text-xs font-bold text-zinc-500">标签<input className="field mt-1" value={tags} onChange={e=>change(setTags,e.target.value)} placeholder="用逗号分隔"/></label>{initial&&<Link href={`/admin/articles/${initial.id}/history`} className="flex items-center gap-2 rounded-xl border border-black/10 px-3 py-2.5 text-sm font-bold dark:border-white/10"><History size={15}/>查看版本历史</Link>}</div></section>
        <section className="panel overflow-hidden"><div className="relative aspect-[16/9] bg-black/5 dark:bg-white/5"><SafeImage src={imageUrl} alt="封面预览" fill sizes="310px" className="object-cover"/></div><div className="space-y-3 p-5"><h2 className="font-black">文章封面</h2><input className="field" value={imageUrl} onChange={e=>change(setImageUrl,e.target.value)} placeholder="图片 URL"/><MediaPicker value={imageUrl} onSelect={url=>{change(setImageUrl,url);setMessage("已从媒体库选择封面")}}/><label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-pink-300 px-3 py-3 text-sm font-black text-pink-500"><ImagePlus size={16}/>上传新封面<input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/avif" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/></label></div></section>{initial&&<button type="button" onClick={remove} className="flex w-full items-center justify-center gap-2 rounded-full border border-red-200 px-5 py-3 text-sm font-bold text-red-500"><Trash2 size={15}/>移入回收站</button>}</aside></div>
  </form>;
}
