"use client";

import { Check, EyeOff, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { AdminTableTools } from "@/components/admin-table-tools";
import { runAdminBulk } from "@/lib/admin-bulk-client";
import type { AdminComment } from "@/lib/types";

export function AdminCommentList({items}:{items:AdminComment[]}){
  const router=useRouter();const [selected,setSelected]=useState<string[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const all=items.length>0&&selected.length===items.length;
  async function action(value:string,ids=selected){if(value==="delete"&&!confirm(`确定删除选中的 ${ids.length} 条评论吗？`))return;setBusy(true);setError("");try{await runAdminBulk("comments",ids,value);setSelected([]);router.refresh()}catch(e){setError(e instanceof Error?e.message:"操作失败")}finally{setBusy(false)}}
  return <div className="panel mt-6 overflow-hidden"><AdminTableTools count={selected.length} busy={busy} onAction={action} actions={[{value:"approve",label:"通过"},{value:"hide",label:"撤回公开"},{value:"delete",label:"删除",danger:true}]}/><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-black/5 bg-zinc-50/70 text-[11px] font-black uppercase tracking-wide text-zinc-400 dark:border-white/10 dark:bg-white/[.025]"><tr><th className="w-12 px-4 py-3"><input type="checkbox" aria-label="全选本页" checked={all} onChange={()=>setSelected(all?[]:items.map(x=>x.id))}/></th><th className="px-2 py-3">评论内容</th><th className="px-4 py-3">作者</th><th className="px-4 py-3">状态</th><th className="px-4 py-3">时间</th><th className="px-4 py-3 text-right">操作</th></tr></thead><tbody className="divide-y divide-black/5 dark:divide-white/10">{items.map(item=><tr key={item.id} className="hover:bg-zinc-50/70 dark:hover:bg-white/[.025]"><td className="px-4 py-3"><input type="checkbox" checked={selected.includes(item.id)} aria-label={`选择${item.author}的评论`} onChange={()=>setSelected(v=>v.includes(item.id)?v.filter(id=>id!==item.id):[...v,item.id])}/></td><td className="max-w-xl px-2 py-3"><p className="line-clamp-2 leading-6 text-zinc-700 dark:text-zinc-200">{item.message}</p><span className="text-[11px] text-zinc-400">文章 #{item.articleId}</span></td><td className="px-4 py-3 font-bold">{item.author}</td><td className="px-4 py-3"><span className={`rounded-md px-2 py-1 text-[11px] font-black ${item.approved?"bg-emerald-500/10 text-emerald-600":"bg-amber-500/10 text-amber-600"}`}>{item.approved?"已公开":"待审核"}</span></td><td className="px-4 py-3 text-xs text-zinc-500">{new Date(item.createdAt).toLocaleDateString("zh-CN")}</td><td className="px-4 py-3"><div className="flex justify-end gap-1">{!item.approved&&<button disabled={busy} onClick={()=>void action("approve",[item.id])} className="rounded-lg p-2 text-emerald-600 hover:bg-emerald-500/10" title="通过"><Check size={15}/></button>}{item.approved&&<button disabled={busy} onClick={()=>void action("hide",[item.id])} className="rounded-lg p-2 text-amber-600 hover:bg-amber-500/10" title="撤回公开"><EyeOff size={15}/></button>}<button disabled={busy} onClick={()=>void action("delete",[item.id])} className="rounded-lg p-2 text-red-500 hover:bg-red-500/10" title="删除"><Trash2 size={15}/></button></div></td></tr>)}{items.length===0&&<tr><td colSpan={6} className="p-10 text-center text-zinc-500">还没有评论。</td></tr>}</tbody></table></div>{error&&<p className="border-t border-red-100 px-4 py-3 text-xs text-red-500">{error}</p>}</div>;
}
