"use client";

import Link from "next/link";
import { ExternalLink, Pencil } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { SafeImage } from "@/components/safe-image";
import { AdminTableTools } from "@/components/admin-table-tools";
import { runAdminBulk } from "@/lib/admin-bulk-client";
import type { AdminArticle } from "@/lib/types";

export function AdminArticleTable({items}:{items:AdminArticle[]}){
  const router=useRouter();const [selected,setSelected]=useState<number[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const all=items.length>0&&selected.length===items.length;
  async function action(value:string){if(value==="delete"&&!confirm(`确定删除选中的 ${selected.length} 篇文章吗？`))return;setBusy(true);setError("");try{await runAdminBulk("articles",selected,value);setSelected([]);router.refresh()}catch(e){setError(e instanceof Error?e.message:"操作失败")}finally{setBusy(false)}}
  return <div className="panel mt-4 overflow-hidden"><AdminTableTools count={selected.length} busy={busy} onAction={action} actions={[{value:"publish",label:"发布"},{value:"hide",label:"转为草稿"},{value:"delete",label:"删除",danger:true}]}/><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-black/5 bg-zinc-50/70 text-[11px] font-black uppercase tracking-wide text-zinc-400 dark:border-white/10 dark:bg-white/[.025]"><tr><th className="w-12 px-4 py-3"><input type="checkbox" aria-label="全选本页" checked={all} onChange={()=>setSelected(all?[]:items.map(x=>x.id))}/></th><th className="px-2 py-3">文章</th><th className="px-4 py-3">分类</th><th className="px-4 py-3">状态</th><th className="px-4 py-3">发布日期</th><th className="px-4 py-3 text-right">操作</th></tr></thead><tbody className="divide-y divide-black/5 dark:divide-white/10">{items.map(item=><tr key={item.id} className="hover:bg-zinc-50/70 dark:hover:bg-white/[.025]"><td className="px-4 py-3"><input type="checkbox" aria-label={`选择${item.title}`} checked={selected.includes(item.id)} onChange={()=>setSelected(v=>v.includes(item.id)?v.filter(id=>id!==item.id):[...v,item.id])}/></td><td className="px-2 py-3"><div className="flex items-center gap-3"><div className="relative h-11 w-14 shrink-0 overflow-hidden rounded-lg"><SafeImage src={item.imageUrl} alt="" fill sizes="56px" className="object-cover"/></div><div className="min-w-0"><b className="block max-w-md truncate">{item.title}</b><span className="text-xs text-zinc-400">/{item.slug}</span></div></div></td><td className="px-4 py-3 text-zinc-500">{item.category}</td><td className="px-4 py-3"><span className={`rounded-md px-2 py-1 text-[11px] font-black ${item.published?"bg-emerald-500/10 text-emerald-600":"bg-zinc-500/10 text-zinc-500"}`}>{item.published?"已发布":"草稿"}</span></td><td className="px-4 py-3 text-xs text-zinc-500">{item.publishedAt?.slice(0,10)||"—"}</td><td className="px-4 py-3"><div className="flex justify-end gap-1"><Link className="rounded-lg p-2 text-zinc-500 hover:bg-pink-50 hover:text-pink-500 dark:hover:bg-pink-500/10" href={`/admin/articles/${item.id}`} title="编辑"><Pencil size={15}/></Link><Link className="rounded-lg p-2 text-zinc-500 hover:bg-zinc-100 dark:hover:bg-white/5" href={`/article/${item.slug}`} target="_blank" title="查看前台"><ExternalLink size={15}/></Link></div></td></tr>)}{items.length===0&&<tr><td colSpan={6} className="p-10 text-center text-zinc-500">没有符合条件的文章。</td></tr>}</tbody></table></div>{error&&<p className="border-t border-red-100 px-4 py-3 text-xs text-red-500">{error}</p>}</div>;
}
