"use client";

import { useEffect, useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { useRouter } from "next/navigation";
import { Check, CloudOff, History, ImagePlus, Save, Trash2 } from "lucide-react";
import type { AdminMoment } from "@/lib/types";
import { SafeImage } from "@/components/safe-image";
import { MediaPicker } from "@/components/media-picker";

function localDateValue(value?:string){const date=value?new Date(value):new Date();const offset=date.getTimezoneOffset()*60_000;return new Date(date.getTime()-offset).toISOString().slice(0,16)}

export function AdminMomentForm({initial}:{initial?:AdminMoment}){
  const router=useRouter();const [content,setContent]=useState(initial?.content??"");const [mood,setMood]=useState(initial?.mood??"动态");const [publishedAt,setPublishedAt]=useState(localDateValue(initial?.publishedAt));const [tags,setTags]=useState(initial?.tags.join(", ")??"");const [imageUrl,setImageUrl]=useState(initial?.imageUrl??"");const [published,setPublished]=useState(initial?.published??false);const [dirty,setDirty]=useState(false);const [online,setOnline]=useState(true);const [message,setMessage]=useState(initial?"已保存":"尚未保存");const draftKey=`nekopress:moment-draft:${initial?.id??"new"}`;
  const change=<T,>(setter:(value:T)=>void,value:T)=>{setter(value);setDirty(true)};
  const save=useMutation({mutationFn:async(publishValue:boolean)=>{const response=await fetch("/api/admin/moments",{method:initial?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:initial?.id,content,mood,publishedAt:new Date(publishedAt).toISOString(),tags:tags.split(/[,，]/).map(x=>x.trim()).filter(Boolean),imageUrl,published:publishValue})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"保存失败");return publishValue},onSuccess:value=>{localStorage.removeItem(draftKey);setDirty(false);setPublished(value);setMessage(value?"动态已公开":"草稿已保存");router.push("/admin/moments");router.refresh()},onError:error=>setMessage(error.message)});
  const removal=useMutation({mutationFn:async()=>{const response=await fetch(`/api/admin/moments?id=${initial?.id}`,{method:"DELETE"});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"删除失败")},onSuccess:()=>{localStorage.removeItem(draftKey);router.push("/admin/moments");router.refresh()},onError:error=>setMessage(error.message)});
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=""}};const on=()=>setOnline(true);const off=()=>setOnline(false);window.addEventListener("beforeunload",warn);window.addEventListener("online",on);window.addEventListener("offline",off);return()=>{window.removeEventListener("beforeunload",warn);window.removeEventListener("online",on);window.removeEventListener("offline",off)}},[dirty]);
  useEffect(()=>{if(!dirty)return;const timer=window.setTimeout(()=>{localStorage.setItem(draftKey,JSON.stringify({content,mood,publishedAt,tags,imageUrl,published,savedAt:new Date().toISOString()}));setMessage(online?"已自动保存到本机":"离线中，草稿已保存在本机")},500);return()=>window.clearTimeout(timer)},[content,mood,publishedAt,tags,imageUrl,published,dirty,draftKey,online]);
  function restoreDraft(){try{const raw=localStorage.getItem(draftKey);if(!raw){setMessage("没有找到本地草稿");return}const draft=JSON.parse(raw);setContent(draft.content??"");setMood(draft.mood??"动态");setPublishedAt(draft.publishedAt??localDateValue());setTags(draft.tags??"");setImageUrl(draft.imageUrl??"");setPublished(Boolean(draft.published));setDirty(true);setMessage(`已恢复本地草稿${draft.savedAt?`（${new Date(draft.savedAt).toLocaleString("zh-CN")}）`:""}`)}catch{setMessage("本地草稿无法读取")}}
  async function upload(file:File){setMessage("正在上传图片…");const formData=new FormData();formData.append("file",file);const response=await fetch("/api/upload",{method:"POST",body:formData});const payload=await response.json();if(!response.ok){setMessage(`上传失败：${payload.error??"未知错误"}`);return}change(setImageUrl,payload.url);setMessage("图片上传成功，等待保存")}
  const busy=save.isPending||removal.isPending;
  return <div className="space-y-5"><header className="sticky top-16 z-20 -mx-4 flex flex-wrap items-center justify-between gap-3 border-b border-black/5 bg-[#f6f7f9]/95 px-4 py-3 backdrop-blur-xl sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8 dark:border-white/10 dark:bg-[#0b0d12]/95"><div><p className={`flex items-center gap-1.5 text-xs font-bold ${!online?"text-red-500":dirty?"text-amber-500":"text-emerald-600"}`}>{!online?<><CloudOff size={13}/>离线，本地草稿已启用</>:dirty?"有未保存修改":<><Check size={13}/>已保存</>}</p><p className="mt-1 text-xs text-zinc-400" aria-live="polite">{message}</p></div><div className="flex flex-wrap gap-2"><button onClick={restoreDraft} className="hidden items-center gap-2 rounded-xl border border-black/10 px-3 py-2 text-xs font-black md:flex dark:border-white/10"><History size={14}/>恢复草稿</button><button disabled={busy} onClick={()=>save.mutate(false)} className="flex items-center gap-2 rounded-xl border border-black/10 bg-white px-3 py-2 text-xs font-black dark:border-white/10 dark:bg-white/5"><Save size={14}/>保存草稿</button><button disabled={busy} onClick={()=>save.mutate(true)} className="btn-primary !rounded-xl !px-4 !py-2"><Save size={14}/>{busy?"处理中…":"公开动态"}</button></div></header>
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_310px]"><section className="panel p-5 sm:p-6"><label className="text-xs font-black text-zinc-500">动态内容<textarea className="field mt-2 min-h-80 resize-y text-base leading-8" maxLength={1000} placeholder="记录此刻的想法…" value={content} onChange={e=>change(setContent,e.target.value)} required/></label><div className="mt-2 text-right text-xs text-zinc-400">{content.length} / 1000</div></section>
      <aside className="space-y-4 xl:sticky xl:top-36"><section className="panel space-y-4 p-5"><h2 className="font-black">发布设置</h2><div className="flex items-center justify-between rounded-xl bg-black/[.03] px-3 py-2.5 text-sm font-bold dark:bg-white/5"><span>当前状态</span><span className={published?"text-emerald-600":"text-zinc-400"}>{published?"已公开":"草稿"}</span></div><label className="block text-xs font-bold text-zinc-500">心情或类型<input className="field mt-1" maxLength={40} value={mood} onChange={e=>change(setMood,e.target.value)} required/></label><label className="block text-xs font-bold text-zinc-500">发布时间<input className="field mt-1" type="datetime-local" value={publishedAt} onChange={e=>change(setPublishedAt,e.target.value)} required/></label><label className="block text-xs font-bold text-zinc-500">标签<input className="field mt-1" value={tags} onChange={e=>change(setTags,e.target.value)} placeholder="用逗号分隔"/></label></section>
        <section className="panel overflow-hidden"><div className="relative aspect-[16/9] bg-black/5 dark:bg-white/5"><SafeImage src={imageUrl} alt="动态图片预览" fill sizes="310px" className="object-cover"/></div><div className="space-y-3 p-5"><h2 className="font-black">配图</h2><input className="field" value={imageUrl} onChange={e=>change(setImageUrl,e.target.value)} placeholder="图片 URL（可选）"/><MediaPicker value={imageUrl} onSelect={url=>change(setImageUrl,url)}/><label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-pink-300 px-3 py-3 text-sm font-black text-pink-500"><ImagePlus size={16}/>上传图片<input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/avif" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file)}}/></label></div></section>
        {initial&&<button disabled={busy} onClick={()=>{if(confirm("确定删除这条动态吗？"))removal.mutate()}} className="flex w-full items-center justify-center gap-2 rounded-xl border border-red-200 px-5 py-3 text-sm font-bold text-red-500"><Trash2 size={15}/>删除动态</button>}
      </aside></div></div>;
}
