"use client";
/* eslint-disable @next/next/no-img-element */
import { Expand, Music2, Pause, Play, RotateCcw, Volume2, VolumeX } from "lucide-react";
import { useRef,useState } from "react";
function clock(value:number){if(!Number.isFinite(value))return "0:00";return `${Math.floor(value/60)}:${String(Math.floor(value%60)).padStart(2,"0")}`}
export function ContentMediaPlayer({kind,src,title,cover,author}:{kind:"audio"|"video";src:string;title?:string;cover?:string;author?:string}){
 const mediaRef=useRef<HTMLMediaElement|null>(null);const shellRef=useRef<HTMLDivElement|null>(null);const [playing,setPlaying]=useState(false);const [current,setCurrent]=useState(0);const [duration,setDuration]=useState(0);const [muted,setMuted]=useState(false);const [failed,setFailed]=useState(false);
 function toggle(){const media=mediaRef.current;if(!media)return;if(media.paused)void media.play();else media.pause()}function seek(value:number){const media=mediaRef.current;if(!media||!duration)return;media.currentTime=value;setCurrent(value)}function toggleMute(){const media=mediaRef.current;if(!media)return;media.muted=!media.muted;setMuted(media.muted)}async function fullscreen(){if(shellRef.current?.requestFullscreen)await shellRef.current.requestFullscreen()}function retry(){setFailed(false);mediaRef.current?.load()}
 const events={onPlay:()=>setPlaying(true),onPause:()=>setPlaying(false),onTimeUpdate:(event:React.SyntheticEvent<HTMLMediaElement>)=>setCurrent(event.currentTarget.currentTime),onLoadedMetadata:(event:React.SyntheticEvent<HTMLMediaElement>)=>setDuration(event.currentTarget.duration),onError:()=>setFailed(true)};
 const playButton=<button type="button" onClick={toggle} aria-label={playing?"暂停":"播放"} className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-pink-500 text-white">{playing?<Pause size={17} fill="currentColor"/>:<Play size={17} fill="currentColor" className="translate-x-px"/>}</button>;
 return <div ref={shellRef} className={`content-player overflow-hidden rounded-2xl border border-black/10 bg-[#11131a] text-white shadow-lg shadow-black/10 dark:border-white/10 ${kind==="audio"?"p-4 sm:p-5":""}`}>
  {kind==="video"?<video ref={node=>{mediaRef.current=node}} src={src} poster={cover||"/images/default-video-cover.svg"} preload="metadata" playsInline onClick={toggle} className="aspect-video w-full bg-black object-contain" {...events}/>:<audio ref={node=>{mediaRef.current=node}} src={src} preload="metadata" {...events}/>} 
  <div className={kind==="video"?"p-3 sm:p-4":"flex items-center gap-4"}>{kind==="audio"&&<div className="relative h-20 w-20 shrink-0 overflow-hidden rounded-2xl"><img src={cover||"/images/default-audio-cover.svg"} alt="" className="h-full w-full object-cover"/><span className="absolute inset-0 grid place-items-center bg-black/15">{playButton}</span></div>}<div className="min-w-0 flex-1"><div className="mb-2 flex min-w-0 items-center gap-2"><Music2 size={14} className="shrink-0 text-pink-400"/><div className="min-w-0"><b className="block truncate text-xs sm:text-sm">{title||`${kind==="audio"?"音频":"视频"}内容`}</b>{author&&<span className="block truncate text-[10px] text-zinc-400">{author}</span>}</div></div><div className="flex items-center gap-2">{kind==="video"&&playButton}<span className="w-9 text-right text-[10px] tabular-nums text-zinc-400">{clock(current)}</span><input aria-label="播放进度" type="range" min={0} max={duration||0} step="0.1" value={Math.min(current,duration||0)} onChange={event=>seek(Number(event.target.value))} className="media-range min-w-0 flex-1"/><span className="w-9 text-[10px] tabular-nums text-zinc-400">{clock(duration)}</span><button type="button" onClick={toggleMute} aria-label={muted?"开启声音":"静音"} className="grid h-8 w-8 shrink-0 place-items-center rounded-full hover:bg-white/10">{muted?<VolumeX size={16}/>:<Volume2 size={16}/>}</button>{kind==="video"&&<button type="button" onClick={()=>void fullscreen()} aria-label="全屏播放" className="grid h-8 w-8 shrink-0 place-items-center rounded-full hover:bg-white/10"><Expand size={16}/></button>}</div></div></div>
  {failed&&<div className="mt-3 flex items-center justify-between gap-3 border-t border-white/10 pt-3 text-xs text-rose-300"><span>媒体加载失败，请检查文件或网络。</span><button type="button" onClick={retry} className="inline-flex shrink-0 items-center gap-1 font-black"><RotateCcw size={13}/>重试</button></div>}
 </div>
}
