"use client";
import { ImagePlus, Music, Video, X } from "lucide-react";
import { useState } from "react";
import { MediaPicker } from "@/components/media-picker";

type Pending={kind:"audio"|"video";url:string};
export function ContentMediaUpload({onInsert}:{onInsert:(markup:string)=>void}){
  const [busy,setBusy]=useState("");const [pending,setPending]=useState<Pending|null>(null);const [title,setTitle]=useState("");const [author,setAuthor]=useState("");const [cover,setCover]=useState("");
  async function upload(file:File|undefined,kind:"image"|"audio"|"video"){if(!file)return;setBusy(kind);const body=new FormData();body.set("file",file);try{const response=await fetch("/api/upload",{method:"POST",body});const result=await response.json();if(!response.ok)throw new Error(result.error||"上传失败");if(kind==="image")onInsert(`![图片描述](${result.url})`);else{setTitle(file.name.replace(/\.[^.]+$/,"")||"媒体标题");setAuthor("");setCover("");setPending({kind,url:result.url})}}catch(reason){window.alert(reason instanceof Error?reason.message:"上传失败")}finally{setBusy("")}}
  function insert(){if(!pending)return;const clean=(value:string)=>value.replace(/[()|]/g," ").trim();onInsert(`@[${pending.kind}](${clean(title)||"媒体标题"})(${pending.url})(${cover})(${pending.kind==="audio"?clean(author):""})`);setPending(null)}
  return <><div className="flex gap-1"><Item label="图片" icon={<ImagePlus size={14}/>} accept="image/jpeg,image/png,image/webp,image/gif,image/avif" busy={busy==="image"} select={file=>void upload(file,"image")}/><Item label="音频" icon={<Music size={14}/>} accept="audio/mpeg,audio/wav,audio/ogg" busy={busy==="audio"} select={file=>void upload(file,"audio")}/><Item label="视频" icon={<Video size={14}/>} accept="video/mp4,video/webm" busy={busy==="video"} select={file=>void upload(file,"video")}/></div>{pending&&<div role="dialog" aria-modal="true" aria-label="设置媒体信息" className="fixed inset-0 z-[120] grid place-items-center bg-black/55 p-4 backdrop-blur-sm"><section className="panel w-full max-w-lg p-5 sm:p-6"><header className="flex items-start justify-between"><div><h2 className="text-xl font-black">设置{pending.kind==="audio"?"音频":"视频"}信息</h2><p className="mt-1 text-xs text-zinc-500">完善标题和封面后插入正文。</p></div><button type="button" aria-label="关闭" onClick={()=>setPending(null)} className="grid h-9 w-9 place-items-center rounded-full bg-black/5 dark:bg-white/5"><X size={16}/></button></header><div className="mt-5 grid gap-4"><label className="text-xs font-bold text-zinc-500">标题<input autoFocus className="field mt-1" value={title} onChange={event=>setTitle(event.target.value)} maxLength={100}/></label>{pending.kind==="audio"&&<label className="text-xs font-bold text-zinc-500">作者 / 嘉宾<input className="field mt-1" value={author} onChange={event=>setAuthor(event.target.value)} maxLength={80} placeholder="选填"/></label>}<label className="text-xs font-bold text-zinc-500">封面地址<input className="field mt-1" value={cover} onChange={event=>setCover(event.target.value)} placeholder="选填，留空使用默认封面"/></label><MediaPicker value={cover} onSelect={setCover}/><div className="flex justify-end gap-2"><button type="button" onClick={()=>setPending(null)} className="page-btn">取消</button><button type="button" onClick={insert} className="btn-primary">插入正文</button></div></div></section></div>}</>
}
function Item({label,icon,accept,busy,select}:{label:string;icon:React.ReactNode;accept:string;busy:boolean;select:(file?:File)=>void}){return <label className="flex cursor-pointer items-center gap-1 rounded-lg px-2 py-2 text-xs font-bold hover:bg-pink-50 hover:text-pink-500 dark:hover:bg-pink-500/10">{icon}{busy?"上传中":label}<input className="sr-only" type="file" accept={accept} disabled={busy} onChange={event=>select(event.target.files?.[0])}/></label>}
