"use client";

import { useMemo, useState } from "react";
import { Check, Images, LoaderCircle, Search, X } from "lucide-react";
import { SafeImage } from "@/components/safe-image";
import type { AdminMediaItem } from "@/lib/admin-data";

export function MediaPicker({ value, onSelect }: { value:string; onSelect:(url:string)=>void }) {
  const [open,setOpen]=useState(false);const [items,setItems]=useState<AdminMediaItem[]>([]);const [query,setQuery]=useState("");const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  const filtered=useMemo(()=>{const images=items.filter(item=>item.mime.startsWith("image/")||/\.(jpe?g|png|webp|gif|avif)$/i.test(item.name));const q=query.trim().toLowerCase();return q?images.filter(item=>`${item.name} ${item.path}`.toLowerCase().includes(q)):images},[items,query]);
  async function show(){setOpen(true);setLoading(true);setError("");try{const response=await fetch("/api/admin/media",{cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error??"媒体库读取失败");setItems(result.items??[])}catch(reason){setError(reason instanceof Error?reason.message:"媒体库读取失败")}finally{setLoading(false)}}
  return <><button type="button" onClick={show} className="flex w-full items-center justify-center gap-2 rounded-xl border border-black/10 px-3 py-3 text-sm font-black transition hover:border-pink-300 hover:text-pink-500 dark:border-white/10"><Images size={16}/>从媒体库选择</button>{open&&<div role="dialog" aria-modal="true" aria-label="选择媒体库图片" className="fixed inset-0 z-[100] flex items-center justify-center bg-black/55 p-4 backdrop-blur-sm" onMouseDown={event=>{if(event.currentTarget===event.target)setOpen(false)}}><section className="panel flex max-h-[86vh] w-full max-w-4xl flex-col overflow-hidden"><header className="flex items-center justify-between border-b border-black/5 p-5 dark:border-white/10"><div><h2 className="text-xl font-black">选择图片</h2><p className="mt-1 text-xs text-zinc-400">点击图片即可设为文章封面</p></div><button type="button" aria-label="关闭" onClick={()=>setOpen(false)} className="grid h-9 w-9 place-items-center rounded-full bg-black/5 dark:bg-white/5"><X size={17}/></button></header><div className="p-4"><label className="relative block"><Search className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-zinc-400" size={16}/><input autoFocus className="field !pl-11" placeholder="搜索文件名或日期…" value={query} onChange={event=>setQuery(event.target.value)}/></label></div><div className="min-h-48 flex-1 overflow-y-auto px-4 pb-5">{loading&&<div className="grid min-h-48 place-items-center text-sm text-zinc-500"><LoaderCircle className="animate-spin"/></div>}{error&&<div className="rounded-xl bg-red-500/10 p-4 text-sm text-red-500">{error}</div>}{!loading&&!error&&filtered.length===0&&<div className="grid min-h-48 place-items-center text-sm text-zinc-500">媒体库中没有符合条件的图片</div>}{!loading&&!error&&<div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4">{filtered.map(item=><button type="button" key={item.path} onClick={()=>{onSelect(item.url);setOpen(false)}} className={`group relative aspect-square overflow-hidden rounded-2xl border-2 transition ${value===item.url?"border-pink-500":"border-transparent hover:border-pink-300"}`}><SafeImage src={item.url} alt={item.name} fill sizes="220px" className="object-cover"/><span className="absolute inset-x-0 bottom-0 truncate bg-gradient-to-t from-black/80 to-transparent px-2 pb-2 pt-8 text-left text-[10px] font-bold text-white">{item.name}</span>{value===item.url&&<span className="absolute right-2 top-2 grid h-7 w-7 place-items-center rounded-full bg-pink-500 text-white"><Check size={14}/></span>}</button>)}</div>}</div></section></div>}</>;
}
