alter table public.articles add column if not exists deleted_at timestamptz;
alter table public.articles add column if not exists deleted_by uuid references auth.users(id) on delete set null;
create index if not exists articles_deleted_at_idx on public.articles (deleted_at, published_at desc);

create table if not exists public.article_versions (
  id bigint generated by default as identity primary key,
  article_id bigint not null references public.articles(id) on delete cascade,
  snapshot jsonb not null,
  change_type text not null default 'update' check (change_type in ('update','restore','trash')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists article_versions_article_idx on public.article_versions (article_id, created_at desc);
alter table public.article_versions enable row level security;
revoke all on public.article_versions from anon, authenticated;
grant all privileges on public.article_versions to service_role;
grant usage, select on all sequences in schema public to service_role;

drop policy if exists "public can read published articles" on public.articles;
create policy "public can read published articles" on public.articles for select using (published = true and deleted_at is null);
