create table if not exists public.media_assets (
  id uuid primary key default gen_random_uuid(),
  path text not null unique,
  public_url text not null unique,
  original_name text not null,
  mime_type text not null,
  media_type text not null check (media_type in ('image','audio','video')),
  size_bytes bigint not null default 0 check (size_bytes >= 0),
  width int check (width is null or width > 0),
  height int check (height is null or height > 0),
  duration_seconds numeric check (duration_seconds is null or duration_seconds >= 0),
  status text not null default 'ready' check (status in ('uploading','ready','failed','trash')),
  uploaded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.media_references (
  id bigint generated by default as identity primary key,
  media_id uuid not null references public.media_assets(id) on delete cascade,
  resource_type text not null check (resource_type in ('article','moment','carousel','site_settings')),
  resource_id text not null,
  field_name text not null,
  created_at timestamptz not null default now(),
  unique (media_id, resource_type, resource_id, field_name)
);

create index if not exists media_assets_created_idx on public.media_assets(created_at desc);
create index if not exists media_assets_type_status_idx on public.media_assets(media_type,status,created_at desc);
create index if not exists media_references_media_idx on public.media_references(media_id);
create index if not exists media_references_resource_idx on public.media_references(resource_type,resource_id);

alter table public.media_assets enable row level security;
alter table public.media_references enable row level security;
revoke all on public.media_assets, public.media_references from anon, authenticated;
grant all on public.media_assets, public.media_references to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.sync_article_media_references()
returns trigger language plpgsql security definer set search_path=public as $$
declare target_id text;
begin
  target_id := case when tg_op='DELETE' then old.id::text else new.id::text end;
  delete from public.media_references where resource_type='article' and resource_id=target_id;
  if tg_op <> 'DELETE' then
    insert into public.media_references(media_id,resource_type,resource_id,field_name)
    select id,'article',new.id::text,'cover' from public.media_assets where public_url=new.image_url and new.image_url<>''
    on conflict do nothing;
    insert into public.media_references(media_id,resource_type,resource_id,field_name)
    select id,'article',new.id::text,'content' from public.media_assets
    where public_url<>'' and position(public_url in new.content::text)>0
    on conflict do nothing;
  end if;
  if tg_op='DELETE' then return old; end if;
  return new;
end $$;

create or replace function public.sync_moment_media_references()
returns trigger language plpgsql security definer set search_path=public as $$
declare target_id text;
begin
  target_id := case when tg_op='DELETE' then old.id::text else new.id::text end;
  delete from public.media_references where resource_type='moment' and resource_id=target_id;
  if tg_op <> 'DELETE' and new.image_url<>'' then
    insert into public.media_references(media_id,resource_type,resource_id,field_name)
    select id,'moment',new.id::text,'image' from public.media_assets where public_url=new.image_url
    on conflict do nothing;
  end if;
  if tg_op='DELETE' then return old; end if;
  return new;
end $$;

create or replace function public.sync_carousel_media_references()
returns trigger language plpgsql security definer set search_path=public as $$
declare target_id text;
begin
  target_id := case when tg_op='DELETE' then old.id::text else new.id::text end;
  delete from public.media_references where resource_type='carousel' and resource_id=target_id;
  if tg_op <> 'DELETE' and new.image_url<>'' then
    insert into public.media_references(media_id,resource_type,resource_id,field_name)
    select id,'carousel',new.id::text,'image' from public.media_assets where public_url=new.image_url
    on conflict do nothing;
  end if;
  if tg_op='DELETE' then return old; end if;
  return new;
end $$;

create or replace function public.sync_settings_media_references()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  delete from public.media_references where resource_type='site_settings' and resource_id='global';
  if tg_op <> 'DELETE' then
    insert into public.media_references(media_id,resource_type,resource_id,field_name)
    select id,'site_settings','global','logo' from public.media_assets where public_url=new.logo_url and new.logo_url<>''
    on conflict do nothing;
    insert into public.media_references(media_id,resource_type,resource_id,field_name)
    select id,'site_settings','global','default_cover' from public.media_assets where public_url=new.default_cover_url and new.default_cover_url<>''
    on conflict do nothing;
  end if;
  if tg_op='DELETE' then return old; end if;
  return new;
end $$;

create or replace function public.sync_new_media_asset_references()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  delete from public.media_references where media_id=new.id;
  insert into public.media_references(media_id,resource_type,resource_id,field_name)
  select new.id,'article',id::text,'cover' from public.articles where image_url=new.public_url and new.public_url<>''
  on conflict do nothing;
  insert into public.media_references(media_id,resource_type,resource_id,field_name)
  select new.id,'article',id::text,'content' from public.articles where new.public_url<>'' and position(new.public_url in content::text)>0
  on conflict do nothing;
  insert into public.media_references(media_id,resource_type,resource_id,field_name)
  select new.id,'moment',id::text,'image' from public.moments where image_url=new.public_url and new.public_url<>''
  on conflict do nothing;
  insert into public.media_references(media_id,resource_type,resource_id,field_name)
  select new.id,'carousel',id::text,'image' from public.carousel_items where image_url=new.public_url and new.public_url<>''
  on conflict do nothing;
  insert into public.media_references(media_id,resource_type,resource_id,field_name)
  select new.id,'site_settings','global','logo' from public.site_settings where logo_url=new.public_url and new.public_url<>''
  on conflict do nothing;
  insert into public.media_references(media_id,resource_type,resource_id,field_name)
  select new.id,'site_settings','global','default_cover' from public.site_settings where default_cover_url=new.public_url and new.public_url<>''
  on conflict do nothing;
  return new;
end $$;

drop trigger if exists sync_article_media_refs on public.articles;
create trigger sync_article_media_refs after insert or update or delete on public.articles for each row execute function public.sync_article_media_references();
drop trigger if exists sync_moment_media_refs on public.moments;
create trigger sync_moment_media_refs after insert or update or delete on public.moments for each row execute function public.sync_moment_media_references();
drop trigger if exists sync_carousel_media_refs on public.carousel_items;
create trigger sync_carousel_media_refs after insert or update or delete on public.carousel_items for each row execute function public.sync_carousel_media_references();
drop trigger if exists sync_settings_media_refs on public.site_settings;
create trigger sync_settings_media_refs after insert or update or delete on public.site_settings for each row execute function public.sync_settings_media_references();
drop trigger if exists sync_new_media_asset_refs on public.media_assets;
create trigger sync_new_media_asset_refs after insert or update on public.media_assets for each row execute function public.sync_new_media_asset_references();
