begin;
create table if not exists public.carousel_items (
  id bigint generated by default as identity primary key,
  article_id bigint not null unique references public.articles(id) on delete cascade,
  sort_order int not null default 0,
  enabled boolean not null default true,
  custom_title text not null default '',
  custom_excerpt text not null default '',
  image_url text not null default '',
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint carousel_valid_window check (ends_at is null or starts_at is null or ends_at > starts_at)
);
create index if not exists carousel_active_order_idx on public.carousel_items (enabled, sort_order);
alter table public.carousel_items enable row level security;
drop policy if exists "public can read active carousel" on public.carousel_items;
create policy "public can read active carousel" on public.carousel_items for select using (enabled = true and (starts_at is null or starts_at <= now()) and (ends_at is null or ends_at > now()));
grant select on public.carousel_items to anon, authenticated;
grant all privileges on public.carousel_items to service_role;
grant usage, select on all sequences in schema public to service_role;
commit;
